inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/*.rb'
  TargetRubyVersion: 2.4

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/AbcSize:
  Max: 19

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
