language: ruby
rvm:
 - 2.4.1
postgres:
  adapter: postgresql
  database: running_club_test
  username: postgres
before_script:
  - "psql -c 'create database running_club_test;' -U postgres"
  - "bundle exec rake db:migrate"
